### ISSUE TITLE
Access Violation for handAverager.addDataPoint

### ISSUE THREAD

**Issue by monajalal** [augcog/OpenARK#2]
Sometimes I get access violation for this line:
`cv::Vec3f handPos = handAverager.addDataPoint(objects[handObjectIndex].getHand().fingers_xyz[0]);`
![acc](https://cloud.githubusercontent.com/assets/1892917/26710824/c5f356c2-4711-11e7-9378-abe6993f9049.PNG)
This usually happens when my hand is not initially captured by the camera and I suddenly bring my hand in front of camera.
Another screenshot:
![errrr](https://user-images.githubusercontent.com/1892917/29301090-acab0776-812e-11e7-871a-4e3d8c4d50d4.PNG)
{sampleFrequency=4 rejectionThreshold=0.10000000000000001 currentValue={...} ...}
handpose: {val=0x00000038aafff2f0 {-0.0131008998, 0.000879988074, 0.304594696} }

**Comment by sxyu** [comment]
probably just needed to check that there was at least 1 finger, anyways no longer appears to be an issue.

**Comment by monajalal** [comment]
Hi Alex, I remember it happened in occurence of hand/fingers. What I remember is it also happened when hand moved fast or when the distance from camera changed so fast but still within scope. Thanks. Glad you fixed it.
