### ISSUE TITLE
Significant lag for PMD camera between the results in Result window and Contour window

### ISSUE THREAD

**Issue by monajalal** [augcog/OpenARK#3]
There's a significant lag between the image in the Result window and the image in the Contour window. Please see the below link in 1080P fullscreen to observe the problem:
https://www.youtube.com/watch?v=UmG5UfE3hSo&feature=youtu.be&hd=1
According to the following screencast, we don't have the same problem with Intel RealSense and there's no lag between the Result window and Contour window for the hand.
https://www.youtube.com/watch?v=pi-puHjhEag&feature=youtu.be&hd=1
*Possible cause of bug is the use of pyrup to scale the acquired image 4x.

**Comment by sxyu** [comment]
for future reference: this kind of "lag" appears because no hand was detected in some frames, so the contour window was not updated in some frames and appeared stuck. If the pyrup was the cause then the whole program should lag, not just one particular window.

**Comment by monajalal** [comment]
The reason Dr Yang suggested it could be because of pyrup is because we use it to rescale the pmd image (while we don't need it in case of realsense images)
