### ISSUE TITLE
handMaxDepth should be changed to double

### ISSUE THREAD

**Issue by joemenke** [augcog/OpenARK#31]
OpenARK/include/DetectionParams.h:110:28: warning: implicit conversion from 'double' to 'int' changes value from 1.6 to 1 [-Wliteral-conversion]
        int handMaxDepth = 1.6;

**Comment by ylshie** [comment]
I try to build code, it fail and stop at Convert.h because of lacking RealSense/SampleReader.h. Where can I found it ?
