### ISSUE TITLE
error: filesystem-no such file or directory.

### ISSUE THREAD

**Issue by Minotaur-CN** [augcog/OpenARK#36]
Dear all,

Some error happens when building . May be wrong version of gcc? 
Thanks!

[ 69%] Building CXX object CMakeFiles/OpenARK.dir/Visualizer.cpp.o
In file included from /home/xx/Tool/OpenARK/MockCamera.cpp:1:0:
/home/xx/Tool/OpenARK/include/MockCamera.h:3:22: fatal error: filesystem: No such file or directory
compilation terminated.
CMakeFiles/OpenARK.dir/build.make:244: recipe for target 'CMakeFiles/OpenARK.dir/MockCamera.cpp.o' failed
make[2]: *** [CMakeFiles/OpenARK.dir/MockCamera.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by akhalili** [comment]
The same error here

**Comment by akhalili** [comment]
solved by adding
-std=c++17 
in CXX flags

Some may need to do the following change:
`#include <filesystem>    -> #include<experimental/filesystem>`
