### ISSUE TITLE
Compile error！

### ISSUE THREAD

**Issue by pureYioYi** [augcog/OpenARK#64]
Hello，thanks for your great code！

I compile this code in win10 with vs2015 and the provided pre-build .exe file, following the instruction of "documentation/Windows-build-instructions-quick.md ".  I suffered from difficulties when building Open3D 0.9.0 and 0.8.0, and the current version I used is 0.7.0.  

There are 2 main errors I met.

Fisrt, “OpenARK\Source\SegmentedMesh.cpp(324): error C2660: "open3d::io::WriteTriangleMeshToPLY": The function does not accept 8 parameters”。

Second,  “OpenARK\Source\SlamDemo435i.cpp(174): error C2039: "isReset": not a member of "okvis::ThreadedKFVio"

And I wondered, which is correct version of Open3D?

Looking forward to your answers. Thanks!

**Comment by joemenke** [comment]
It looks like you are using the new version of the code with the old version of the dependencies installer. Apologies, the dependencies installer was updated on Wednesday. The new version should include Open3D as part of the dependencies installer, and fix the okvis issue.

**Comment by TheBricktop** [comment]
Would You consider using Github Actions to automate building process and provide us with artifacs?
@joemenke

**Comment by pureYioYi** [comment]
> It looks like you are using the new version of the code with the old version of the dependencies installer. Apologies, the dependencies installer was updated on Wednesday. The new version should include Open3D as part of the dependencies installer, and fix the okvis issue.

Thanks for your reply, and I succeed with the new version of  dependecies installer
