### ISSUE TITLE
Cannot find C:\Program Files\OpenARK-Deps/CMakeLists.txt

### ISSUE THREAD

**Issue by zhaozj89** [augcog/OpenARK#66]
Following [Build Instructions for Windows Using Pre-Built Dependencies](https://github.com/augcog/OpenARK/blob/master/documentation/Windows-build-instructions-quick.md), when I executated `cmake .. -G"Visual Studio 14 2015 Win64"`, it said `CMake Error at CMakeLists.txt:61 (include): include could not find load file: C:\Program Files\OpenARK-Deps/CMakeLists.txt`, and it could not find dependencies like OpenCV, etc.

When I examined the folder `C:\Program Files\OpenARK-Deps`, there was not a cmake file. I would like to ask whether the dependency installer configures the cmake file (although the instruction says it is) or what I did wrong. Thank you.

![Capture](https://user-images.githubusercontent.com/34164876/90082630-daffd200-dd42-11ea-89ce-00c179723a35.PNG)

![Capture2](https://user-images.githubusercontent.com/34164876/90082635-e05d1c80-dd42-11ea-8cde-fb255a25c278.PNG)

**Comment by adamchang2000** [comment]
Hi zhaozj! Sorry for the confusion. You should be running the cmake commands from the folder containing OpenARK itself, not the dependencies. You can get the OpenARK code by running `git clone https://github.com/augcog/openark`. Then follow the build instructions from the PDF.
